// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Allowed `postMessage` target origins.
 *
 * The bridge handshake (ADR-10 §D4) establishes this list at session start;
 * the receiver enforces it. Same-origin BroadcastChannel does not require
 * origin verification (the browser guarantees same-origin); deep-link
 * transport carries no origin and falls back to bridge-id verification.
 *
 * We model this as a string-typed enum on the Rust side so consumer code
 * matches exhaustively; the TS export keeps the literal union shape
 * receivers can `===` against.
 */
export type AgentActionTargetOrigin = string;
