// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason an agent departed the topology. Currently a single normative value
 * because agentbox emits `agent_removed` without an explicit reason; the
 * enum exists so consumers can pattern-match exhaustively and future
 * reasons can be added without breaking the wire shape (additive).
 */
export type DepartReason = "removed";
