// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of the GitHub adapter for one source file.
 *
 * The domain receives this via `IngestPage` / `IngestOntologyOnly`
 * commands and never sees raw HTTP responses, `octocrab` types, or
 * corpus-specific frontmatter / wikilink syntax. That insulation has since
 * been exercised: when the authored corpus moved from a Logseq graph to an
 * Obsidian vault (ADR-2040), only the adapter changed and this value object
 * stayed stable.
 *
 * The corpus format is specified by `docs/VAULT-corpus-format.md`: §V2 YAML
 * frontmatter is the metadata carrier, and a leading Logseq `key:: value`
 * property block is still accepted under the bounded legacy tolerance of
 * ADR-2040 D3, which ends at the `review_trigger` on that record.
 *
 * `frontmatter_json` and `jsonld_blocks` are deliberately `serde_json::Value`
 * because:
 *
 * - Frontmatter is open-ended: §V2 gives meaning to a fixed set of keys and
 *   preserves every other key verbatim.
 * - JSON-LD blocks must round-trip without loss for the ontology parser.
 *
 * The richer DDD-08 fields (`prose_blocks`, `ontology_blocks`,
 * `outbound_wikilinks`) are domain projections built *from* this raw shape;
 * they belong in the Section 8 parser, not in this cross-boundary contract.
 */
export type ParsedMarkdown = { 
/**
 * Repo-relative path, normalised to forward slashes.
 * (Section 8 calls this `path`; we use `canonical_path` to make the
 * normalisation guarantee explicit at the boundary.)
 */
canonical_path: string, 
/**
 * Raw file body, UTF-8.
 */
raw: string, 
/**
 * Parsed vault frontmatter as a JSON object
 * (`docs/VAULT-corpus-format.md` §V2). Keys preserved verbatim. Under the
 * ADR-2040 legacy tolerance the adapter also accepts a leading Logseq
 * property block, normalising `public:: true` into `{"public": true}`
 * per DDD-08 §"To Section 10" — both carriers reach the domain in the
 * one shape.
 */
frontmatter_json: Record<string, unknown>, 
/**
 * JSON-LD block bodies, one per block, order preserved. In the vault
 * these are plain `json-ld` code fences in the page body (§V3); in the
 * legacy corpus they sat under a `### OntologyBlock` heading.
 */
jsonld_blocks: Array<Record<string, unknown>>, 
/**
 * Git blob SHA1 (40 hex chars). Used by the SHA1-gated sync.
 */
commit_sha: string, };
